# Generated by Django 3.0.3 on 2020-05-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='picture',
        ),
    ]
