# Generated by Django 3.0.3 on 2020-05-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200507_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Designation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='mstatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.MaritalStatus'),
            preserve_default=False,
        ),
    ]
