# Generated by Django 3.0.3 on 2020-05-09 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200507_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.IntegerField()),
                ('da', models.IntegerField()),
                ('ta', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('ma', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Designation')),
            ],
        ),
    ]
