# Generated by Django 3.0.3 on 2020-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='total',
            new_name='e_total',
        ),
        migrations.AddField(
            model_name='salary',
            name='r_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
